function AprimeMST(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'aprimeinstructions',...
     '../input/AprimeMST/practice.txt',...
     ['../output/AprimeMST/practice' num2str(subjNo) '.csv'],...
     '../input/AprimeMST/most.txt',...
     ['../output/AprimeMST/' num2str(subjNo) '.csv'],...
     42,... % break interval
     0 ); % final 1 = debug
end