function ColorsMST(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'colorsinstructions',...
     '../input/ColorsMST/colors practice - most.txt',...
     ['../output/Colors/practice/practice' num2str(subjNo) '.csv'],...
     '../input/ColorsMST/colors items - most.txt',...
     ['../output/Colors/' num2str(subjNo) '.csv'],...
     61,... % break interval
     1 ); % final 1 = debug
end