function PMST(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'primeinstructions',...
     '../input/PMST/practice.txt',...
     ['../output/PMSTMTH/practice/practice' num2str(subjNo) '.csv'],...
     '../input/PMST/most.txt',...
     ['../output/PMSTMTH/' num2str(subjNo) '.csv'],...
     51,... % break interval
     1 ); % final 1 = debug
end