function PrimeMST(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'primeinstructions',...
     '../input/PrimeMST/practice.txt',...
     ['../output/Prime/practice/practice' num2str(subjNo) '.csv'],...
     '../input/PrimeMST/most.txt',...
     ['../output/Prime/' num2str(subjNo) '.csv'],...
     60,... % break interval
     1 ); % final 1 = debug
end