function ColorsMTH(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'colorsinstructions',...
     '../input/ColorsMTH/colors practice - more than half.txt',...
     ['../output/Colors/practice/practice' num2str(subjNo) '.csv'],...
     '../input/ColorsMTH/colors items - more than half.txt',...
     ['../output/Colors/' num2str(subjNo) '.csv'],...
     61,... % break interval
     1 ); % final 1 = debug
end