function Test(subjNo)
    RunExperimentWithInstructionsAndPractice(...
     'prminstructions',...
     '../input/GeneratorTest/Test1.txt',...
     ['../output/GeneratorTest/Test1' num2str(subjNo) '.csv'],...
      '../input/GeneratorTest/Test2.txt',...
     ['../output/GeneratorTest/Test2' num2str(subjNo) '.csv'],...
     41,... % break interval
     1 ); % final 1 = debug
end